# This file was generated by GoReleaser. DO NOT EDIT.
class Setup < Formula
  desc "Setup your local dev environment with one command."
  homepage ""
  url "https://github.com/radar/setup/releases/download/0.3.7/setup_0.3.7_darwin_amd64.tar.gz"
  version "0.3.7"
  sha256 "9792e3a1d32ea3463ed946b62f1e21bad175cdc1f7ea7c3555d404de5f79c4c1"

  def install
    bin.install "setup"
  end
end
