# This file was generated by GoReleaser. DO NOT EDIT.
class Setup < Formula
  desc "Setup your local dev environment with one command."
  homepage ""
  url "https://github.com/radar/setup/releases/download/0.3.9/setup_0.3.9_darwin_amd64.tar.gz"
  version "0.3.9"
  sha256 "0583df1b9d782b6aff323e591b8af8bf73eb03c7183df4f5d6b501358ee4b7e3"

  def install
    bin.install "setup"
  end
end
