# This file was generated by GoReleaser. DO NOT EDIT.
class Setup < Formula
  desc "Setup your local dev environment with one command."
  homepage ""
  url "https://github.com/radar/setup/releases/download/0.4.0/setup_0.4.0_darwin_amd64.tar.gz"
  version "0.4.0"
  sha256 "e2f6edf7a734a8441d50fcc4059e94fc1d24bff47ae04170b23e660962264c1f"

  def install
    bin.install "setup"
  end
end
