# This file was generated by GoReleaser. DO NOT EDIT.
class Setup < Formula
  desc "Setup your local dev environment with one command."
  homepage ""
  url "https://github.com/radar/setup/releases/download/0.5.0/setup_0.5.0_darwin_amd64.tar.gz"
  version "0.5.0"
  sha256 "da4fd8aa61a7068f28ca91d1b23eeb556f9138d4a36cb18baf1b3cb6387b4ef3"
  
  depends_on "asdf"

  def install
    bin.install "setup"
  end
end
